name: linter
on: [push]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up node
      uses: actions/setup-node@v1
    - run: npm install -g jsonlint dockerfilelint
    - run: jsonlint **.json --quiet --compact
    - run: dockerfilelint ./web/Dockerfile

